### ISSUE TITLE
Suggestion for phone.

### ISSUE THREAD

**Issue by AgentGrunt** [InZidiuZ/LegacyRP-feedback#142]
**Suggester:**
John Pilgrim Agent_Grunt#0344

**Summary:**
Add a function to the phone for people to post their jobs(yellow/white pages). For example, Taxi driver makes a post with his/her number so others can find it with ease. Another example is for Lawyers/ Mechanics to post about them being in town to help people when in trouble.  

**Reason:**
It would add another great aspect of RP for a lot different players that are trying to create a story without spamming twitter.

**Economy:**
Only effect is people may actually get hired to do their jobs.

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. We plan on moving twitter over to the phone instead of chat, and will do the same thing with business ads.

**Nateღ**
_Legacy RP Staff & Developer_
