### ISSUE TITLE
Afkrs get rid of em.

### ISSUE THREAD

**Issue by teheenew** [InZidiuZ/LegacyRP-feedback#146]
Get a timer for the AFK'rs that are around. 15~minutes afk = kick... Some seem to pass this and use some ingame thing to stay online... Making alot of $$$ while not being online actually.

**Comment by N8teZero** [comment]
Hey,

I do not believe we will be looking to implement an AFK kick system. This causes issues for RP as we'd need to be sure not to kick someone who is handcuffed in a situation or otherwise staying still for RP reasons. So instead, the staff typically will scan the online players(especially if there is a queue) and see if players are AFK.

**Nateღ**
_Legacy RP Staff & Developer_

**Comment by teheenew** [comment]
Cant you make it that if someone is handcuffed it to be an action instead of being afk? This can override the system so they wouldn't be kicked but actual players would be for being afk.
