### ISSUE TITLE
Suggestion PD unmarked vehicles

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#28]
####  Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
Add more unmarked PD vehicles
https://www.gta5-mods.com/vehicles/2008-chevrolet-tahoe-unmarked-slicktop
https://www.gta5-mods.com/vehicles/2012-unmarked-dodge-charger-hd
https://www.gta5-mods.com/vehicles/lapd-unmarked-2016-dodge-charger-pursuit

#### Reason: Why would your suggestion be a good addition to Legacy?
Add more Roleplay to the PD for special operations.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by InZidiuZ** [comment]
Suggestion approved. Two out of the three linked vehicles have been added to the server. One of the dodge chargers were ignored due to (1) duplicates and (2) unbalanced handling which I was (3) too lazy to fix. Do keep in mind these vehicles are _not_ to be overused, and I request you to have a maximum amount of _2_ unmarked vehicles on patrol when the server is full, and there's at least 4 other regular vehicles on patrol.
